-- Migration: Add meal_type to meals, day_of_week and menu_structured to nutrition_plan_menus
-- Date: 2026-01-17

-- 1. Add meal_type column to meals table
-- Possible values: breakfast, lunch, dinner, snack
ALTER TABLE meals ADD COLUMN IF NOT EXISTS meal_type VARCHAR(20) DEFAULT 'snack';

-- 2. Add day_of_week column to nutrition_plan_menus (0=Monday, 6=Sunday)
ALTER TABLE nutrition_plan_menus ADD COLUMN IF NOT EXISTS day_of_week INTEGER;

-- 3. Add menu_structured column to nutrition_plan_menus table
-- This will store the structured JSON menu generated by AI
ALTER TABLE nutrition_plan_menus ADD COLUMN IF NOT EXISTS menu_structured JSONB;

-- 4. Make date column nullable (we use day_of_week now)
ALTER TABLE nutrition_plan_menus ALTER COLUMN date DROP NOT NULL;

-- 5. Drop unique constraint on (plan_id, date) if exists, add new one for day_of_week
ALTER TABLE nutrition_plan_menus DROP CONSTRAINT IF EXISTS nutrition_plan_menus_plan_id_date_key;
CREATE UNIQUE INDEX IF NOT EXISTS idx_nutrition_plan_menus_plan_day 
  ON nutrition_plan_menus(plan_id, day_of_week) WHERE day_of_week IS NOT NULL;

-- 6. Create indexes
CREATE INDEX IF NOT EXISTS idx_meals_meal_type ON meals(meal_type);
CREATE INDEX IF NOT EXISTS idx_nutrition_plan_menus_day ON nutrition_plan_menus(plan_id, day_of_week);
